services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent volume

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./logs:/app/logs  # Explicitly will map /app/logs to host logs dir
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

volumes:
  pgdata:
  logs:  # Host mount: docker-compose will create ./logs on host