# Generated by Django 5.2.7 on 2025-10-21 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('items', models.JSONField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hash_key', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
